# Generated by Django 5.0.4 on 2024-05-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='material',
            table='materials',
        ),
    ]
